version: 0.0
os: linux
files:
  - source: /
    destination: /var/consulta-ui
hooks:
  ApplicationStart:
    - location: /var/consulta-ui/scripts/start_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /var/consulta-ui/scripts/copy_files.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /var/consulta-ui/scripts/stop_server.sh
      timeout: 300
      runas: root