version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - npm i

artifacts:
  files:
    - appspec.yml
    - scripts/*
    - index.html